<?php $en_zh=array (
  'yunqi' => '运气',
  'huahui' => '花卉',
  'zhiwu' => '植物',
  'qiancheng' => '前程',
  'word' => '事业',
  'suiyuejinghao' => '岁月静好',
  'hunyin' => '婚姻',
  'meiniu' => '美妞',
  'my' => '我的',
  'gsdf' => '告诉对方刚',
  'gfd' => '个还是东方红',
  'fgdf' => '和法国恢复',
  'caiyun' => '财运',
);?>